@rest
Feature: JSON convert to file or variable

  Scenario: Convert Json schema to json as file
    Given I convert jsonSchema '{"type":"object","additionalProperties":false,"properties":{"general":{"type":"object","additionalProperties":false,"ui":null,"name":"general","title":"General","description":"General","properties":{"serviceId":{"description":"ServiceID","type":"string","required":true,"readOnly":false,"application":true,"level":1,"internalName":"SERVICE_ID","title":"ServiceID","default":"serv-qa-verify-apis"}},"required":["serviceId"]},"environment":{"type":"object","additionalProperties":false,"ui":null,"name":"environment","title":"Environment","description":"Environment","properties":{"instance":{"type":"string","required":true,"readOnly":false,"application":true,"level":1,"internalName":"INSTANCE","title":"Instance","default":"crossdata-1"},"stringVaultHost":{"type":"string","readOnly":true,"application":false,"level":1,"globalParameter":"globals.vault.vaultHost","internalName":"STRING_VAULT_HOST","title":"Stringvaulthost","default":"vault.service.eos.india.pit"},"vaultPort":{"type":"number","readOnly":false,"application":false,"level":1,"internalName":"VAULT_PORT","title":"Vaultport","default":8200}},"required":["instance"]}}}' to json and save it in file 'testJson.json'
    And I run 'cat $(pwd)/target/test-classes/testJson.json' locally

  Scenario: Convert Json schema to json as variable
    Given I convert jsonSchema '{"type":"object","additionalProperties":false,"properties":{"general":{"type":"object","additionalProperties":false,"ui":null,"name":"general","title":"General","description":"General","properties":{"serviceId":{"description":"ServiceID","type":"string","required":true,"readOnly":false,"application":true,"level":1,"internalName":"SERVICE_ID","title":"ServiceID","default":"serv-qa-verify-apis"}},"required":["serviceId"]},"environment":{"type":"object","additionalProperties":false,"ui":null,"name":"environment","title":"Environment","description":"Environment","properties":{"instance":{"type":"string","required":true,"readOnly":false,"application":true,"level":1,"internalName":"INSTANCE","title":"Instance","default":"crossdata-1"},"stringVaultHost":{"type":"string","readOnly":true,"application":false,"level":1,"globalParameter":"globals.vault.vaultHost","internalName":"STRING_VAULT_HOST","title":"Stringvaulthost","default":"vault.service.eos.india.pit"},"vaultPort":{"type":"number","readOnly":false,"application":false,"level":1,"internalName":"VAULT_PORT","title":"Vaultport","default":8200}},"required":["instance"]}}}' to json and save it in variable 'testJson'
    And I run 'echo '!{testJson}'' locally

  Scenario: Convert Json schema to json as variable as file
    Given I convert jsonSchema '{"type":"object","additionalProperties":false,"properties":{"general":{"type":"object","additionalProperties":false,"ui":null,"name":"general","title":"General","description":"General","properties":{"serviceId":{"description":"ServiceID","type":"string","required":true,"readOnly":false,"application":true,"level":1,"internalName":"SERVICE_ID","title":"ServiceID","default":"serv-qa-verify-apis"}},"required":["serviceId"]},"environment":{"type":"object","additionalProperties":false,"ui":null,"name":"environment","title":"Environment","description":"Environment","properties":{"instance":{"type":"string","required":true,"readOnly":false,"application":true,"level":1,"internalName":"INSTANCE","title":"Instance","default":"crossdata-1"},"stringVaultHost":{"type":"string","readOnly":true,"application":false,"level":1,"globalParameter":"globals.vault.vaultHost","internalName":"STRING_VAULT_HOST","title":"Stringvaulthost","default":"vault.service.eos.india.pit"},"vaultPort":{"type":"number","readOnly":false,"application":false,"level":1,"internalName":"VAULT_PORT","title":"Vaultport","default":8200}},"required":["instance"]}}}' to json and save it in variable 'testJson' and save it in file 'testJson.json'
    And I run 'echo '!{testJson}'' locally
    And I run 'cat $(pwd)/target/test-classes/testJson.json' locally